export const listOfWMS = [
    'WMS-Hoydetall',
    // 'wms-std-demo',
    // 'WMS-TEMADATA',
    'WMS-TILTAK',
    // 'wms-wae-komtek-innbygger',
    // 'WMS-VA',
    // 'wms-fkb-bygg',
    // 'WMS-NMK',
    // 'wms-finn-orto',
    // 'wms-finn-orto-hist',
    // 'wms-finn-kart',
    // 'wms-finn-hybrid',
    // 'wms-vektor-standard',
    // 'wms-vektor-lite',
    // 'wms-vektor-medium',
    // 'wms-orto',
    // 'wms-orto-hist',
    'wms-matrikkelkart',
    // 'wms-standardkart',
    // 'wms-takhelning',
    // 'WMS-VEKTOR-GRAY',
    // 'WMS-PLAN',
    // 'WMS-KOMMUNEDATA',
    // 'WMS-TEMADATA-KOMTEK',
    'wms-vegkategori'
];
